name: Spiel manuell bauen

# Dadurch wird der manuelle Startknopf aktiviert
on:
  workflow_dispatch:

# Diese Variable zwingt GitHub Actions, Node.js 24 zu nutzen und behebt die Warnung
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  build-Bindoj:
    runs-on: windows-latest
    
    # Hier werden die minimalen Rechte für diesen Job festgelegt
    permissions:
      contents: read
      
    steps:
      - name: Code herunterladen
        uses: actions/checkout@v6

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.5'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Spiel mit PyInstaller bauen
        run: pyinstaller main.spec

      - name: Fertiges Spiel speichern
        uses: actions/upload-artifact@v4
        with:
          name: Spiel-Bindoj-Build
          path: dist/
